version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: brainlending 
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234


  backend:
    build: ./Backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./Backend/src:/app
    ports:
      - "8000:8000"


  frontend:
    build: ./Frontend
    volumes:
      - ./Frontend/src:/app
      - /app/node_modules
    ports:
      - "8080:8080"